### PR TITLE
Add first draft material for testing

### PR DESCRIPTION
**Pull request by uekerman**
- `intro_slides.md` is kind of ready to use, but we could probably shorten it.
- `python_testing_*.md` is material (slides, demo, exercise), we used in the SSE lecture. Sth like this, we would need for Julia and our stats example.

### CODE REVIEW

**Comment by behinger** [comment]
- Code-Coverage: I actually never programmed it myself, just use the code from PkgTemplates.jl :-D
Have you read into it already - especially regarding the demo?
- further I propose to have them run tests on their mystats functions, and in the demos we use something else

**Comment by behinger** [comment]
ok - I started converting stuff to Julia.

- I cannot get a floating point assertion to fail :-D maybe you are more lucky than I am. I did use the one you proposed in python... :shrug:

- I did not implement a regression test - I dont really got the idea I think. In what way is this better than hardcoding an expected value + generating a random number stream with a `StableRNG`?
- Didnt yet go for coverage, maybe you can have a look
- Didnt go through the exercise yet

PS: Corona in the house - let's see when I can work on it again :D

**Comment by uekerman** [comment]
Let's try to put all lecture content into one `slides.md` similar to #13 
Let's drop coverage, we anyway have to shorten things. Will come with `PkgTemplates.jl`.

**Comment by behinger** [comment]
I added the MyStatsPackage, I didnt want to copy my function so I import it with a relative path which resides outside of the package, which is really bad style because it requires the MyStatsPackage to stay exactly where it is in terms of absolute paths. But if you keep that in mind you should be fine ;)

For your tests just copy it to `./MyStatsPackage/src/statistics.jl`

**Comment by uekerman** [comment]
Demo should be ready, only open TODO is the exercise.

**Comment by uekerman** [comment]
Ready for review / merge from my side.

**Pull request merged**
