### PR TITLE
Changed schedule from image to text 

### PR DESCRIPTION
**Pull request by debruine**
Text tables are better for accesibility and copy/paste-ability. We could also link each lesson entry to a landing page for that session?

(also updated to fix my name ;)

### CODE REVIEW

**Comment by debruine** [comment]
Slides for the simulation section are still using R; I will update those for Julia soon. (fixed now)

**Comment by behinger** [comment]
Hey this is really great. can I merge already to have the schedule?

**Comment by debruine** [comment]
Yes, of course! My slides are in the next two commits and they're fine to put up, too. I'm still working on the workshop materials for Thursday, and will send a pull request for that soon.

(Do I have to resolve the merge conflict with the updated _quarto.yml file, or can you do that, @behinger?)

**Comment by behinger** [comment]
regarding quarto merge conflict, did you change more than the links to your parts? Unfortunately git gave the whole file as merge conflict...

**Pull request merged**
